### ISSUE TITLE
create fakeps in C and compare its performance with the Python version

### ISSUE THREAD

**Issue by klaeufer** [LoyolaChicagoCode/processtree-ansi-c#2]
- should preallocate the entire array 
- should probably use a simple, bare-metal linked list similar to the one in processtree.c

**Comment by gkthiruvathukal** [comment]
This is quick and dirty, but here is what I am seeing (awful performance on the Python side):

time python fakeps.py 100000
real    0m32.964s
user    0m32.534s
sys 0m0.276s

C++ version (sorry, I am not doing pure C):
real    0m0.514s
user    0m0.240s
sys 0m0.069s
